In [ ]:
Задание 1.

In [ ]:
import numpy as np

In [38]:
a = np.array([[1, 2, 3, 3, 1], [6, 8, 11, 10, 7]])
a

array([[ 1,  2,  3,  3,  1],
       [ 6,  8, 11, 10,  7]])

In [40]:
b = a.T
b

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [41]:
mean_a = b.mean(axis=0)
mean_a

array([2. , 8.4])

Задание 2.

In [17]:
a_centered = np.subtract(b, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [ ]:
Задание 3.

In [43]:
a_centered_sp = a_centered.T[0] @ a_centered.T[1]/4
a_centered_sp

2.0

In [42]:
a_centered_sp = np.dot(a_centered.T[0], a_centered.T[1])/4
a_centered_sp

2.0